# Shipyard developer tasks. See docs/DEVELOPMENT.md.

SHELL := /bin/bash
.DEFAULT_GOAL := help

GO      ?= go
BIN_DIR ?= bin
PKG     := github.com/hami9/shipyard
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT  ?= $(shell git rev-parse HEAD 2>/dev/null)
LDFLAGS := -s -w -X $(PKG)/internal/buildinfo.version=$(VERSION) -X $(PKG)/internal/buildinfo.commit=$(COMMIT)

# staticcheck 2026.2.1. It cannot yet analyze Go 1.27, hence the go1.26 toolchain pin in go.mod.
STATICCHECK := honnef.co/go/tools/cmd/staticcheck@v0.8.1
# Reports only vulnerabilities in code the binaries can reach [GO-VULNCHECK].
GOVULNCHECK := golang.org/x/vuln/cmd/govulncheck@v1.8.0

# GoReleaser is installed as a binary, not `go run`, because it needs a newer Go
# than go.mod pins and `go run` would pass that toolchain on to the release build.
GORELEASER_VERSION := v2.18.2
GORELEASER         := $(BIN_DIR)/tools/goreleaser

# Local development database (deploy/dev/compose.yaml). Dev-only credentials.
DEV_COMPOSE                ?= docker compose -f deploy/dev/compose.yaml
SHIPYARD_DATABASE_URL      ?= postgres://shipyard:shipyard@127.0.0.1:54320/shipyard?sslmode=disable
SHIPYARD_TEST_DATABASE_URL ?= postgres://shipyard:shipyard@127.0.0.1:54320/postgres?sslmode=disable
# Dev-only KEK, generated by `make dev-kek` into an ignored directory.
SHIPYARD_KEK_DIR           ?= $(CURDIR)/.dev/kek
SHIPYARD_KEK_ACTIVE        ?= dev
# The worker's log socket, read by the API (ADR-0008).
SHIPYARD_WORKER_SOCKET     ?= $(CURDIR)/.dev/logs.sock

.PHONY: help build test lint vuln fmt test-integration test-docker test-e2e dev-up dev-down dev-reset dev-kek migrate run-api run-worker release-check release-snapshot web-types web-check web-build web-dev test-ui clean

help: ## List targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-18s %s\n", $$1, $$2}'

build: ## Build static binaries into ./bin
	CGO_ENABLED=0 $(GO) build -trimpath -ldflags '$(LDFLAGS)' -o $(BIN_DIR)/ ./cmd/...

test: ## Unit tests with the race detector
	$(GO) test -race ./...

lint: ## gofmt check, go vet, staticcheck (unit, integration, and docker files)
	@out="$$(gofmt -l .)"; if [ -n "$$out" ]; then echo "gofmt needed on:"; echo "$$out"; exit 1; fi
	$(GO) vet ./...
	$(GO) vet -tags integration,docker,e2e ./...
	$(GO) run $(STATICCHECK) ./...
	$(GO) run $(STATICCHECK) -tags integration,docker,e2e ./...

vuln: ## govulncheck: known vulnerabilities in reachable code (Go and modules)
	$(GO) run $(GOVULNCHECK) ./...
	$(GO) run $(GOVULNCHECK) -tags integration,docker,e2e ./...

fmt: ## Format all Go files
	gofmt -w .

web-types: ## Regenerate web/src/api/schema.ts from api/openapi.json (ADR-0015)
	$(GO) test ./internal/openapits -run TestGenerated -update

web-check: ## The web UI: npm ci, tsc, its tests, and a production build into web/dist (Node.js 24+)
	cd web && npm ci --no-audit --no-fund && npm run check && npm test && npm run build

web-build: ## Build the web UI into web/dist for the server archive (Node.js 24+; GoReleaser runs it)
	cd web && npm ci --no-audit --no-fund && npm run build

test-ui: ## The web UI's Playwright tests against a real API and PostgreSQL (make dev-up; Node.js 24, Chromium)
	cd web && npm ci --no-audit --no-fund && npx playwright install chromium && \
	  SHIPYARD_TEST_DATABASE_URL='$(SHIPYARD_TEST_DATABASE_URL)' npx playwright test

web-dev: ## The web UI on http://127.0.0.1:5173, proxying /v1 to SHIPYARD_API_URL (default the run-api address)
	cd web && npm run dev

test-integration: ## Integration tests against PostgreSQL (run `make dev-up` first)
	SHIPYARD_TEST_DATABASE_URL='$(SHIPYARD_TEST_DATABASE_URL)' $(GO) test -race -tags integration ./...

test-docker: ## Tests that need Docker Engine and buildx (owner's machine, not CI)
	# -p 1: one package at a time. Each package's Caddy edge joins every app
	# network on the host (as the one production edge must), so packages
	# running in parallel would attach to each other's test networks.
	$(GO) test -race -tags docker -count=1 -p 1 ./...

test-e2e: ## End-to-end deploy through the real binaries (Docker, buildx, git; run `make dev-up` first)
	SHIPYARD_TEST_DATABASE_URL='$(SHIPYARD_TEST_DATABASE_URL)' $(GO) test -tags e2e -count=1 -timeout 45m -v ./test/e2e

dev-up: ## Start local PostgreSQL 18 (Docker, bound to 127.0.0.1:54320)
	$(DEV_COMPOSE) up -d --wait

dev-down: ## Stop local services; keeps the data volume
	$(DEV_COMPOSE) down

dev-reset: ## Stop local services and delete their data
	$(DEV_COMPOSE) down -v

migrate: ## Apply migrations to $SHIPYARD_DATABASE_URL
	SHIPYARD_DATABASE_URL='$(SHIPYARD_DATABASE_URL)' $(GO) run ./cmd/shipyard-api migrate

dev-kek: ## Create the dev KEK in .dev/kek (once; never use it in production)
	@mkdir -p '$(SHIPYARD_KEK_DIR)' && chmod 700 '$(SHIPYARD_KEK_DIR)'
	@f='$(SHIPYARD_KEK_DIR)/$(SHIPYARD_KEK_ACTIVE).key'; \
	  if [ ! -f "$$f" ]; then (umask 077 && head -c 32 /dev/urandom > "$$f") && echo "created $$f"; fi

run-api: dev-kek ## Run the API against the dev database (127.0.0.1:8080; no DNS preflight for domains)
	SHIPYARD_DATABASE_URL='$(SHIPYARD_DATABASE_URL)' SHIPYARD_KEK_DIR='$(SHIPYARD_KEK_DIR)' SHIPYARD_KEK_ACTIVE='$(SHIPYARD_KEK_ACTIVE)' \
	  SHIPYARD_WORKER_SOCKET='$(SHIPYARD_WORKER_SOCKET)' SHIPYARD_DNS_PREFLIGHT=false SHIPYARD_LOG_FORMAT=text $(GO) run ./cmd/shipyard-api serve

run-worker: dev-kek ## Run the worker against the dev database (needs Docker and buildx; Caddy on 127.0.0.1:18081/18443)
	SHIPYARD_DATABASE_URL='$(SHIPYARD_DATABASE_URL)' SHIPYARD_KEK_DIR='$(SHIPYARD_KEK_DIR)' SHIPYARD_KEK_ACTIVE='$(SHIPYARD_KEK_ACTIVE)' \
	  SHIPYARD_WORK_DIR='$(CURDIR)/.dev/work' SHIPYARD_CADDY_ADMIN_DIR='$(CURDIR)/.dev/caddy' SHIPYARD_CADDY_BIND=127.0.0.1 \
	  SHIPYARD_CADDY_HTTP_PORT=18081 SHIPYARD_CADDY_HTTPS_PORT=18443 SHIPYARD_CADDY_CA=internal \
	  SHIPYARD_WORKER_SOCKET='$(SHIPYARD_WORKER_SOCKET)' SHIPYARD_LOG_FORMAT=text $(GO) run ./cmd/shipyard-worker run

$(GORELEASER):
	GOBIN=$(CURDIR)/$(BIN_DIR)/tools $(GO) install github.com/goreleaser/goreleaser/v2@$(GORELEASER_VERSION)

release-check: $(GORELEASER) ## Validate .goreleaser.yaml
	$(GORELEASER) check

release-snapshot: $(GORELEASER) ## Build release archives and images locally into ./dist (nothing is published)
	env -u GOTOOLCHAIN $(GORELEASER) release --snapshot --clean

clean: ## Remove build and release output
	rm -rf $(BIN_DIR) dist
